apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sample-app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sample-app-secret
  data:
    - secretKey: notesPlain
      remoteRef:
        key: eso-smoke-test/notesPlain
